'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.296
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ontolog_Module.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property appunti_architetto_franc_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appunti_architetto_franc_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Attributes_bamboo_danny_allen_r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attributes bamboo_danny_allen_r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_down_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_down_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_down_minus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_down_minus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_minus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_minus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_up_Infinite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_up_Infinite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_up_plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_up_plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property base_checkmark_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("base_checkmark_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bb_home_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bb_home_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bb_reload_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bb_reload_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bb_sort2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bb_sort2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DoubleRightArrowHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DoubleRightArrowHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Export_to_DB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Export_to_DB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Procedures() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Procedures", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pulsante_01_architetto_f_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pulsante_01_architetto_f_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pulsante_01_architetto_f_01_First() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pulsante_01_architetto_f_01_First", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pulsante_02_architetto_f_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pulsante_02_architetto_f_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pulsante_02_architetto_f_01_Last() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pulsante_02_architetto_f_01_Last", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RelationTypes_gpride_jean_victor_balin_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RelationTypes gpride_jean_victor_balin_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property slim_cd_drive_frederic_m_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("slim_cd_drive_frederic_m_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tasto_3_architetto_franc_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tasto_3_architetto_franc_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tasto_4_architetto_franc_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tasto_4_architetto_franc_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tasto_8_architetto_franc_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tasto_8_architetto_franc_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Types_Closed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Types_Closed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vogelschwarm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vogelschwarm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property XSDSchema_SequenceIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XSDSchema_SequenceIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
